### ISSUE TITLE
What crypto does twik use? 

### ISSUE THREAD

**Issue by lahwran** [gustavomondron/twik#11]
The readme doesn't seem to say.

**Comment by murderered** [comment]
There is no real crypto done. Your master password, a tag (for example service name) and your private key gets combined and hashed (this is done with md5 and sha1). So its more like concatening and hashing.

Look into app/src/main/java/com/reddyetwo/hashmypass/app/hash/PasswordHasher.java for more details. 

Since your master password is not saved, it does not need to be encrypted.

**Comment by lahwran** [comment]
if there's no crypto used, then the tool is useless. those are crypto, though. it's not encryption, but those are cryptographic hash functions - *broken* cryptographic hash functions. could you make a mode where it uses a SHA256-based HMAC? (don't use straight-up SHA256, as it's vulnerable to a length extension attack, if I understand correctly). 

Also, can I use the tool without a saved private key, only remembering my password? I can remember enough bits of entropy, and I really don't like storing things.

**Comment by gustavomondron** [comment]
Hi @lahwran , SHA1 was chosen for compatibility reasons. Initially, we didn't have extensions for Chrome or Firefox so the passwords generated using Twik needed to be 100% compatible with the Password Hasher Plus extension, which uses SHA1.

Now, Twik is available for Chrome, Firefox, Android and Python so it's possible to go further and use a different hash function. Actually, this is something we had in mind since the beginning, and will be implemented ASAP.

Regarding making the private key optional, I think it's safer to use it, but I understand that for some people disabling it may fit better their needs. I'll think of the best way to implement this feature. It's not technically difficult at all but it requires some work on that part of the tutorial.

**Comment by nothingmuch** [comment]
Just add a note telling to set the private key to all zeros for people who don't want that extra security, with a link to further explanation on why it's a good idea?
