### ISSUE TITLE
Sync / Export & Import

### ISSUE THREAD

**Issue by JeremyWW** [gustavomondron/twik#17]
Hi,

Sorry if this has already been covered somewhere. I have Twik on my Android phone. Is it in some way possible to sync / export & import profiles & keys from Chrome on my laptop to Twik on the phone. Am I missing a trick here somewhere?

**Comment by daMihe** [comment]
Hello,

i'm sorry, there is currently no possibility to sync profiles of twik on android with the plugin for chrome. But they use the same algorithm. The same private key will generate same passwords. So you can sync it by hand, just create a profile and type in the key from the other device. Since in normal use you don't change the private key often i think thats okay until a synchronization exists. The disadvantage is that you need to setup all customized pages in your second client again.

There is also an idea for synchronizing twik implementations in Issue #14.

**Comment by gustavomondron** [comment]
I'm sorry for the long delay. Thank you for your question and thanks also to @murderered for your answer. As aforementioned, this is going to be addressed as part of Issue [#14](https://github.com/gustavomondron/twik/issues/14).
